version: '3.9'

services:
  farm-management-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farm-management-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
